# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20160725_1254'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together=set([('product', 'registered_date', 'shop')]),
        ),
    ]
